const treeDatabase = {
    arts: {
        nodes: [
            //row1
            {
                id: "design-concepts",
                label: "Design<br>Concepts",
                icon: "Art_Icons/Design_Concepts.png",
                title: "Design Concepts",
                type: "Arts Skill",
                req: "",
                desc: "Foundational principles of visual design, including composition, layout, and color theory.",
                descLong: "My understanding of visual design principles was established during my Associate's program studying Interactive Media. I completed coursework in Digital Design Concepts to understand how to structure visual information effectively.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "1 / 2"
            },
            {
                id: "sketching",
                label: "Sketching",
                icon: "Art_Icons/Sketching.png",
                title: "Sketching",
                type: "Arts Skill",
                req: "",
                desc: `Producing physical and digital drawings to explore visual concepts, capture forms, and establish proportions.`,
                descLong: "I have sketched periodically throughout my life and completed two courses during my Associate's program that involved working with pencil, colored pencils, and graphite. I am proficient with sketching from references, focusing my practice on capturing form and proportion.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "1 / 3"
            },
            //row2
            {
                id: "writing",
                label: "Writing",
                icon: "Art_Icons/Writing.png",
                title: "Writing",
                type: "Arts Skill",
                req: "",
                desc: "Composing structured text, narrative elements, and technical documentation.",
                descLong: "I structure narrative and technical writing for game documents and text-based experiences. I ensure documentation is clear, functional, and organized for proper project scoping and development.",
                points: "3/3",
                pointClass: "full",
                gridPos: "2 / 1"
            },
            {
                id: "audio",
                label: "Audio",
                icon: "Art_Icons/Audio.png",
                title: "Audio",
                type: "Arts Skill",
                req: "Requires Something",
                desc: "Recording, editing, and implementing sound effects and music tracks.",
                descLong: "I have a foundational understanding of music theory and introductory experience with keyboards. I utilize software such as Audacity and navigate basic Digital Audio Workstations to edit existing audio tracks for engine implementation.",
                points: "1/3",
                pointClass: "partial",
                gridPos: "2 / 2"
            },
            {
                id: "figure-drawing",
                label: "Figure<br>Drawing",
                icon: "Art_Icons/Figure_Drawing.png",
                title: "Figure Drawing",
                type: "Arts Skill",
                req: "Requires Sketching",
                desc: `Studying and capturing the human form through live observation and gesture studies.`,
                descLong: "I completed a Drawing the Human Form course in my Associate's Program. I have also executed figure drawing gesture studies and speed sketches independently to practice form and proportion.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "2 / 4"
            },
            //row3
            {
                id: "art-3d",
                label: "3D Art",
                icon: "Art_Icons/3D.png",
                title: "3D Art",
                type: "Arts Skill",
                req: "Requires Something",
                desc: "Modeling and shaping three-dimensional digital objects and environments.",
                descLong: "I utilize Blender for 3D modeling, having explored the software through periodic tutorials over the past fifteen years. I also established an understanding of 3D asset pipelines by completing a 3D Modeling for Game Design course using Maya during my Associate's degree.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "3 / 2"
            },
            {
                id: "art-2d",
                label: "2D Art",
                icon: "Art_Icons/2D.png",
                title: "2D Art",
                type: "Arts Skill",
                req: "Requires Sketching",
                desc: "Creating two-dimensional digital graphics and modifying existing visual assets.",
                descLong: "My focus in 2D digital art centers on modifying existing assets and creating functional graphics for games, as I typically source free assets for the majority of my personal projects. This practical work ensures familiarity with art pipelines and engine requirements.",
                points: "1/3",
                pointClass: "partial",
                gridPos: "3 / 3"
            },
            //row4
            {
                id: "texture-uv",
                label: "Texture<br>UV",
                icon: "Art_Icons/texture.png",
                title: "Texture UV",
                type: "Arts Skill",
                req: "Requires 3D Art",
                desc: "Projecting a 2D image onto a 3D model's surface for texture application.",
                descLong: "I can unwrap 3D models and arrange UV layouts for texturing. I have executed these pipeline tasks within Blender and have experience establishing UV structures for WebGL implementations.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "4 / 2"
            },
            {
                id: "raster",
                label: "Raster",
                icon: "Art_Icons/Raster.png",
                title: "Raster",
                type: "Arts Skill",
                req: "Requires 2D Art",
                desc: "Editing and manipulating pixel-based imagery, photos, and UI icons.",
                descLong: "I am highly proficient in photo editing and the creation of simple pixel graphics using software like GIMP, which I have used since childhood. I completed Digital Imaging and Media coursework during my Associate's program, which was done using Adobe Photoshop, and routinely manipulate raster images to fit specific game engine requirements.",
                points: "3/3",
                pointClass: "full",
                gridPos: "4 / 3"
            },
            {
                id: "vector",
                label: "Vector",
                icon: "Art_Icons/Vector.png",
                title: "Vector",
                type: "Arts Skill",
                req: "Requires 2D Art",
                desc: "Creating scalable, mathematically defined digital graphics and illustrations.",
                descLong: "I learned the basic interfaces and tools of Inkscape and Adobe Illustrator during my Associate's degree, including coursework in Digital Illustration & Animation. I understand the fundamental difference between vector and raster formats within the production pipeline.",
                points: "1/3",
                pointClass: "partial",
                gridPos: "4 / 4"
            },
            //row5
            {
                id: "anim-3d",
                label: "3D Animation",
                icon: "Art_Icons/3D_anim.png",
                title: "3D Animation.",
                type: "Arts Skill",
                req: "Requires 3D Art and Rigging",
                desc: "Animating three-dimensional models and environments across timelines.",
                descLong: "I understand foundational 3D animation principles from previous academic coursework in high school. I am familiar with the concepts of keyframing and timeline manipulation, alongside camera and lighting set-ups, within a three-dimensional workspace.",
                points: "1/3",
                pointClass: "partial",
                gridPos: "5 / 1"
            },
            {
                id: "rigging",
                label: "Rigging",
                icon: "Art_Icons/rigging.png",
                title: "Rigging",
                type: "Arts Skill",
                req: "",
                desc: "Constructing digital skeletons and control structures to deform and animate models.",
                descLong: "I understand the mechanical processes required to rig a model for animation. My practical experience of these concepts is focused on implementing 2D bone-based animations within the Godot engine.",
                points: "1/3",
                pointClass: "partial",
                gridPos: "5 / 2"
            },
            {
                id: "anim-2d",
                label: "2D Animation",
                icon: "Art_Icons/2D_anim.png",
                title: "2D Animation",
                type: "Arts Skill",
                req: "Requires 2D Art and Rigging",
                desc: "Creating movement and motion sequences using two-dimensional digital assets.",
                descLong: "I manipulate screen elements over time using video editors and game engines. I completed Motion Graphics and digital animation coursework at Quinsigamond Community College, focusing on positional animation rather than traditional frame-by-frame drawing.",
                points: "1/3",
                pointClass: "partial",
                gridPos: "5 / 3"
            },
            //row6
            {
                id: "ui-ux",
                label: "UI/UX<br>Design",
                icon: "Art_Icons/ui_ux.png",
                title: "UI/UX Design",
                type: "Arts Skill",
                req: "",
                desc: "Designing user interfaces and optimizing the user experience for digital applications.",
                descLong: "I design functional interfaces that prioritize user navigation and clear information display. The focus is on establishing intuitive layouts that communicate game mechanics or application functions effectively.",
                points: "3/3",
                pointClass: "full",
                gridPos: "6 / 2"
            },
            //row7
            {
                id: "web-design",
                label: "Web<br>Design",
                icon: "Art_Icons/web_design.png",
                title: "Web Design",
                type: "Arts Skill",
                req: "Requires UI/UX Design",
                desc: "Structuring and designing visual layouts and interfaces for web environments.",
                descLong: "I build web layouts and structure user interfaces. I approach web design by focusing on clean navigation hierarchies and ensuring elements are positioned logically within the browser environment.",
                points: "3/3",
                pointClass: "full",
                gridPos: "7 / 2"
            },
        ],
        connections: [
            {from: 'sketching', to: 'art-2d', type: 'straight'},
            {from: 'sketching', to: 'figure-drawing', type: 'elbow'},
            {from: 'art-3d', to: 'texture-uv', type: 'straight'},
            {from: 'art-3d', to: 'anim-3d', type: 'left-elbow'},
            {from: 'art-2d', to: 'raster', type: 'straight'},
            {from: 'art-2d', to: 'vector', type: 'elbow'},
            {from: 'raster', to: 'anim-2d', type: 'straight'},
            {from: 'rigging', to: 'anim-3d', type: 'straight'},
            {from: 'rigging', to: 'anim-2d', type: 'straight'},
            {from: 'ui-ux', to: 'web-design', type: 'straight'},
        ]
    },
    games: {
        nodes: [
            //row1
            {
                id: "game-fundamentals",
                label: "Game<br>Design<br> Fundamentals",
                icon: "Game_Icons/gd_fundamentals.png",
                title: "Game Design Fundamentals",
                type: "Games Skill",
                req: "",
                desc: "Core principles of game design, including mechanics, player psychology, and interaction loops.",
                descLong: "My understanding of game design fundamentals has been developed through academic coursework, independent study, and practical application across digital and analog formats. I apply these concepts to structure mechanics, manage pacing, and establish clear progression.",
                points: "3/3",
                pointClass: "full",
                gridPos: "1 / 2"
            },
            //row2
            {
                id: "narrative-design",
                label: "Narrative<br>Design",
                icon: "Game_Icons/narrative.png",
                title: "Narrative Design",
                type: "Games Skill",
                req: "Requires Game Design Fundamentals",
                desc: "Structuring interactive stories, integrating narrative elements. and applying world-building directly into game mechanics.",
                descLong: "I have studied narrative design through independent courses and tutorials. I have applied these concepts practically by engineering interactive, branching text-based experiences using tools like Twine, blending story progression with conditional logic.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "2 / 1"
            },
            {
                id: "system-design",
                label: "System<br>Design",
                icon: "Game_Icons/system_design.png",
                title: "System Design",
                type: "Games Skill",
                req: "Requires Game Design Fundamentals",
                desc: "Creating and balancing the underlying rules, economies, and mathematical systems that govern gameplay.",
                descLong: "I design and balance interrelated game systems, frequently blending genres and prioritizing unique mechanics as the primary driver for play. I applied these principles directly to my project, Arena, structuring rule sets and interlocking systems to dictate the flow of the game and provide distinct tactical choices.",
                points: "3/3",
                pointClass: "full",
                gridPos: "2 / 2"
            },
            {
                id: "level-design",
                label: "Level<br>Design",
                icon: "Game_Icons/level_design.png",
                title: "Level Design",
                type: "Level Design",
                req: "Requires Game Design Fundamentals",
                desc: "Crafting playable environments that guide player movement, pace challenges, and support core mechanics.",
                descLong: "My level design experience is primarily focused on 2D environments. I build layouts that introduce mechanics progressively, facilitate spatial flow, and control game pacing within custom engine setups.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "2 / 3"
            },
            //row3
            {
                id: "digital",
                label: "Digital<br>Design",
                icon: "Game_Icons/digital_design.png",
                title: "Digital Design",
                type: "Games Skill",
                req: "",
                desc: "The specific application of game design principles to digital mediums and video game software.",
                descLong: "I have a firm understanding of digital design paradigms across a wide variety of genres, developed through extensive gameplay experience and analysis. Practically, I have developed roughly a half-dozen small games and prototypes outside of guided tutorials, primarily focusing on 2D experiences.",
                points: "3/3",
                pointClass: "full",
                gridPos: "3 / 2"
            },
            {
                id: "tabletop",
                label: "Tabletop<br>Design",
                icon: "Game_Icons/tabletop_design.png",
                title: "Tabletop Design",
                type: "Arts Skill",
                req: "",
                desc: "Designing mechanics, rulesets, and physical components for non-digital board, card, and roleplaying games.",
                descLong: "I have drafted custom mechanics and built physical models through analog design exercises prior to digital implementation. This practical design work is informed by a familiarity with rule interactions gained from playing TCGs and running TTRPG campaigns.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "3 / 4"
            },
            //row4
            {
                id: "rapid-prototyping",
                label: "Rapid<br>Prototyping",
                icon: "Game_Icons/prototyping.png",
                title: "Rapid Prototyping",
                type: "Games Skill",
                req: "Requires Tabletop Design",
                desc: "Quickly developing functional models of game mechanics to test viability and iterate on core concepts.",
                descLong: "I build functional, isolated prototypes to quickly validate core mechanics and fail fast. I have developed these bare-minimum test builds for digital concepts across multiple engines, and utilize paper prototyping for tabletop mechanics to test viability before committing to full production",
                points: "3/3",
                pointClass: "full",
                gridPos: "4 / 4"
            },
            //row5
            {
                id: "gameplay-programming",
                label: "Gameplay<br>Programming",
                icon: "Game_Icons/gameplay_programming.png",
                title: "Gameplay Programming",
                type: "Games Skill",
                req: "Requires Digital Design",
                desc: "Translating game design documentation and mechanics into functional code within a game engine.",
                descLong: "I program core game logic, character controllers, and system interactions. I have experience scripting mechanics across multiple engines, utilizing programming languages such as C++, C#, and GDScript to bring design concepts to functional states.",
                points: "3/3",
                pointClass: "full",
                gridPos: "5 / 2"
            },
            //row6
            {
                id: "unity",
                label: "Unity<br>Game<br>Engine",
                icon: "Game_Icons/Unity.png",
                title: "Unity Game Engine",
                type: "Games Skill",
                req: "Requires Gameplay Programming",
                desc: "Developing digital games utilizing the Unity engine.",
                descLong: "I utilized Unity extensively during my Associate's program. I am familiar with its component-based architecture and UI implementation to script interactions and build functional digital environments.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "6 / 1"
            },
            {
                id: "godot",
                label: "Godot<br>Game<br>Engine",
                icon: "Game_Icons/Godot.png",
                title: "Godot Game Engine",
                type: "Games Skill",
                req: "Requires Gameplay Programming",
                desc: "Developing 2D and 3D games utilizing the Godot engine and GDScript.",
                descLong: "I have comprehensive knowledge of the Godot engine, having read the entire official documentation. I leverage its node-based scene architecture and GDScript to construct hierarchies and build responsive 2D mechanics natively.",
                points: "3/3",
                pointClass: "full",
                gridPos: "6 / 2"
            },
            {
                id: "unreal",
                label: "Unreal<br>Game<br>Engine",
                icon: "Game_Icons/Unreal.png",
                title: "Unreal Game Engine",
                type: "Games Skill",
                req: "Requires Gameplay Programming",
                desc: "Developing digital games utilizing the Unreal Engine environment and its associated systems.",
                descLong: "I have a foundational familiarity with Unreal Engine. I understand the general structure and interface of the environment and have studied C++ in academic settings.",
                points: "1/3",
                pointClass: "partial",
                gridPos: "6 / 3"
            },
            {
                id: "game-process",
                label: "Game<br>Development<br>Process",
                icon: "Game_Icons/gd_process.png",
                title: "Game Development Process",
                type: "Games Skill",
                req: "",
                desc: "The production pipeline of scheduling, scoping, and coordinating a game from concept to completion.",
                descLong: "I have an understanding of the game development pipeline, including  of how art and software pipelines integrate during cross-discipline studio interaction. For my 2D tactical RPG and deck-builder project, Acolytes, I will serve as the producer, establishing the initial project scope and assigning production tasks to coordinate a multidisciplinary team.",
                points: "3/3",
                pointClass: "full",
                gridPos: "6 / 4"
            },
            //row7
            {
                id: "pitching",
                label: "Pitching",
                icon: "Game_Icons/pitching.png",
                title: "Pitching",
                type: "Games Skill",
                req: "Requires Game Development Process",
                desc: "Formulating and presenting game concepts to potential team members or faculty.",
                descLong: "I have experience structuring and delivering project pitches. For Acolytes, I formulated the core vision and scope, successfully pitching the concept to both university faculty and students to secure approval and recruiting my development team.",
                points: "3/3",
                pointClass: "full",
                gridPos: "7 / 4"
            },
        ],
        connections: [
            {from: 'game-fundamentals', to: 'narrative-design', type: 'left-elbow'},
            {from: 'game-fundamentals', to: 'system-design', type: 'straight'},
            {from: 'game-fundamentals', to: 'level-design', type: 'elbow'},
            {from: 'digital', to: 'gameplay-programming', type: 'straight'},
            {from: 'tabletop', to: 'rapid-prototyping', type: 'straight'},
            {from: 'gameplay-programming', to: 'unity', type: 'left-elbow'},
            {from: 'gameplay-programming', to: 'godot', type: 'straight'},
            {from: 'gameplay-programming', to: 'unreal', type: 'elbow'},
            {from: 'game-process', to: 'pitching', type: 'straight'},
        ]
    },
    computers: {
        nodes: [
            //row1
            {
                id: "architecture",
                label: "Architecture",
                icon: "Computer_Icons/architecture.png",
                title: "Architecture",
                type: "Computers Skill",
                req: "",
                desc: "How computer hardware and software interface at a low level, including interfacing with RAM and CPU, threading, and other related concepts.",
                descLong: "I have learned about the high-level interactions between computer hardware through academic coursework and personal study.<br><br>My formal study of architecture is currently in progress, as I am registered for Introduction to Machine Organization and Assembly Language, alongside several Electrical and Computer Engineering courses.",
                points: "1/3",
                pointClass: "partial",
                gridPos: "1 / 1"
            },
            {
                id: "programming-concepts",
                label: "Programming<br>Concepts",
                icon: "Computer_Icons/concepts.png",
                title: "Programming Concepts",
                type: "Computers Skill",
                req: "",
                desc: "The theoretical and structural paradigms of writing software, including object-oriented design, algorithms, and systems programming.",
                descLong: "I have a foundation in programming concepts established through academic coursework and practical application.<br><br>I have taken university courses in Object-Oriented Design, Systems Programming Concepts, and Algorithms. I apply these structures to author game logic and have helped to architect scalable deployment systems in a professional environment.",
                points: "3/3",
                pointClass: "full",
                gridPos: "1 / 2"
            },
            //row2
            {
                id: "dev-process",
                label: "Development<br>Process",
                icon: "Computer_Icons/dev_process.png",
                title: "Development Process",
                type: "Computers Skill",
                req: "",
                desc: "The methodologies and pipelines used to plan, construct, test, and deploy software in a professional environment, including agile software development.",
                descLong: "I gained experience with the software development process as a Software Engineering Contractor at Cisco and regularly use practices such as version control in my personal projects.<br><br>I have experience with Git, GitHub, and Jira in the context of professional teams.",
                points: "3/3",
                pointClass: "full",
                gridPos: "2 / 1"
            },
            {
                id: "programming-languages",
                label: "Programming<br>Languages",
                icon: "Computer_Icons/programming_languages.png",
                title: "Programming Languages",
                type: "Computers Skill",
                req: "Requires Programming Concepts",
                desc: "Proficiency in coding languages used across software engineering, scripting, web development, and game development.",
                descLong: "I am proficient in Python and Bash from my time engineering deployment pipelines at Cisco. Academically, I have utilized Java and C for algorithms and systems programming<br><br>I have experience with multiple programming languages from academic and personal study, and I regularly learn new languages as needed, with a preference for Python.",
                points: "3/3",
                pointClass: "full",
                gridPos: "2 / 2"
            },
            {
                id: "math",
                label: "Math",
                icon: "Computer_Icons/Math.png",
                title: "Math",
                type: "Computers Skill",
                req: "",
                desc: "Mathematical foundations critical for computer science, including calculus, linear algebra, discrete math, and probability.",
                descLong: "I have completed university-level coursework up to Calculus IV, as well as Discrete Mathematics, Applied Statistics, Probability, and Linear Algebra.",
                points: "3/3",
                pointClass: "full",
                gridPos: "2 / 4"
            },
            //row3
            {
                id: "networking",
                label: "Networking",
                icon: "Computer_Icons/networking.png",
                title: "Networking",
                type: "Computers Skill",
                req: "",
                desc: "The protocols and infrastructure that allow devices and systems to communicate across networks.",
                //also read that whole book cisco networking
                descLong: "At Cisco, I worked directly with network infrastructures, engineering telemetry platforms that handled real-time data from approximately 2,500 routers.<br><br>To supplement this enterprise experience with formal theory, I am enrolled in a Computer Networks course. I have read Cisco Networking Simplified and am familiar with networking concepts such as the layers of the OSI Model. I have also hosted projects using GitHub Pages and Node.js.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "3 / 1"
            },
            {
                id: "web-frameworks",
                label: "Web<br>Frameworks",
                icon: "Computer_Icons/web_frameworks.png",
                title: "Web Frameworks",
                type: "Computers Skill",
                req: "Requires Networking, Programming Languages, and HTML/CSS",
                desc: "Utilizing architectural frameworks to develop, maintain, and scale web applications and services.",
                descLong: "My primary experience with web frameworks involves Django, which I utilized at Cisco to maintain deployment pipelines handling real-time router telemetry. I also have familiarity with React and AngularJS.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "3 / 2"
            },
            {
                id: "html-css",
                label: "HTML/<br>CSS",
                icon: "Computer_Icons/html.png",
                title: "HTML/CSS",
                type: "Computers Skill",
                req: "",
                desc: "The fundamental markup and styling languages used to structure and visually format content across the web.",
                descLong: "I am comfortable using HTML and CSS to build user interfaces and web content. I have created several web projects, including this portfolio website, using HTML, CSS, and JavaScript. I have also created a text-based game using Twine integrated with custom HTML and CSS, and I have exported games to HTML.",
                points: "3/3",
                pointClass: "full",
                gridPos: "3 / 3"
            },
            //row4
            {
                id: "databases",
                label: "Databases",
                icon: "Computer_Icons/databases.png",
                title: "Databases",
                type: "Computers Skill",
                req: "",
                desc: "Structuring, querying, and maintaining data storage systems for applications.",
                descLong: "During my time at Cisco, I architected containerized infrastructure configurations that supported router data visualization. This required working directly with TimescaleDB, PostgreSQL, and Redis. I have taken online courses using SQL and will be taking Database Systems at the university level.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "4 / 1"
            },
            {
                id: "full-stack",
                label: "Full<br>Stack<br>Development",
                icon: "Computer_Icons/fullstack.png",
                title: "Full Stack Development",
                type: "Computers Skill",
                req: "Requires Web Databases, Web Frameworks, and Message Brokers",
                desc: "Developing and integrating front-end user interfaces with back-end infrastructures of software applications.",
                descLong: "My engineering experience at Cisco required an understanding of the full stack to facilitate deployments. I was responsible for integrating back-end Django pipelines, databases, and message brokers to ensure the front-end telemetry platforms functioned reliably.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "4 / 2"
            },
            {
                id: "message-brokers",
                label: "Message<br>Brokers",
                icon: "Computer_Icons/message.png",
                title: "Message Brokers",
                type: "Computers Skill",
                req: "",
                desc: "Intermediary software modules that route, translate, and manage real-time data streams between distributed applications.",
                descLong: "To manage real-time router telemetry at Cisco, we utilized RabbitMQ and Kafka. These message brokers were essential in ensuring that data streams from thousands of routers were processed reliably without dropping telemetry payloads.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "4 / 3"
            },
            //row5
            {
                id: "dev-ops",
                label: "Dev Ops",
                icon: "Computer_Icons/dev_ops.png",
                title: "Dev Ops",
                type: "Computers Skill",
                req: "Requires Full Stack Development",
                desc: "The alignment of software development and IT operations to optimize CI/CD workflows and provide continuous delivery.",
                descLong: "As a deployment contractor for Cisco, I maintained Docker-based pipelines and engineered multi-stage deployment strategies. I developed custom Bash and Python automation that reduced deployment latency and minimized manual intervention for complex integrations.",
                points: "3/3",
                pointClass: "full",
                gridPos: "5 / 2"
            },
            {
                id: "containers",
                label: "Containers",
                icon: "Computer_Icons/containers.png",
                title: "Containers",
                type: "Computers Skill",
                req: "",
                desc: "Packaging software code and its dependencies into isolated units to ensure consistent execution across different environments.",
                descLong: "I have professional experience architecting containerized infrastructure using Docker and Kubernetes. At Cisco, I designed and maintained Docker-based pipelines to support deployments, streamlining environments for distributed teams.",
                points: "3/3",
                pointClass: "full",
                gridPos: "5 / 3"
            },
            //row6
            {
                id: "os",
                label: "Operating<br>Systems",
                icon: "Computer_Icons/os.png",
                title: "Operating Systems",
                type: "Computers Skill",
                req: "",
                desc: "Proficiency in navigating, configuring, and developing within major operating systems.",
                descLong: "I am comfortable developing and troubleshooting across Windows, macOS, and Linux/Unix environments. Professionally, I utilized Unix for deployment scripting at Cisco. To deepen my structural and theoretical understanding of these environments, I will be taking a dedicated Operating Systems course in the future.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "6 / 1"
            },
            {
                id: "computer-graphics",
                label: "Computer<br>Graphics",
                icon: "Computer_Icons/CG.png",
                title: "Computer Graphics",
                type: "Computers Skill",
                req: "Requires Math",
                desc: "Generating, rendering, and manipulating visual imagery using programmatic mathematics and graphic APIs.",
                descLong: "I have established a foundation in computer graphics through academic coursework at WPI. I have executed matrix transformations in WebGL to render scenes, and I am enrolled in Computer Graphics to expand my knowledge of rendering techniques. I will also be taking Computer Animation in the future as a direct follow-up to my WebGL coursework.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "6 / 4"
            },
            //row7
            {
                id: "sys-admin",
                label: "System<br>Administration",
                icon: "Computer_Icons/sysadmin.png",
                title: "System Administration",
                type: "Computers Skill",
                req: "Requires Operating Systems",
                desc: "Configuring, maintaining, and operating computer systems, servers, and automated protocols for distributed teams.",
                descLong: "While my background is centered on software engineering and DevOps, these roles often require system administration. I have experience setting up and troubleshooting servers and virtual machines in clustered environments. This work involved handling administrative tasks such as disk partitioning, configuring networking, and authoring standard operating procedures to ensure system stability.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "7 / 1"
            },
            {
                id: "docs",
                label: "Documentation",
                icon: "Computer_Icons/documentation.png",
                title: "Documentation",
                type: "Computers Skill",
                req: "",
                desc: "Writing and maintaining structured technical guides, deployment protocols, and project design documents.",
                descLong: "At Cisco, I authored technical documentation to standardize deployment protocols for distributed engineering teams.",
                points: "3/3",
                pointClass: "full",
                gridPos: "7 / 2"
            },
            {
                id: "ai",
                label: "Artificial<br>Intelligence",
                icon: "Computer_Icons/AI.png",
                title: "Artificial Intelligence",
                type: "Computers Skill",
                req: "",
                desc: "The foundational logic and algorithmic structures required to simulate decision-making or intelligent behavior in software.",
                descLong: "My background as a programmer and game developer provides a foundation in the logic structures, state machines, and algorithmic decision-making that serve as the building blocks for AI. To formally develop this skill set, I will be taking three dedicated classes next year: Machine Learning, Introduction to Artificial Intelligence, and Artificial Intelligence in Games.",
                points: "1/3",
                pointClass: "partial",
                gridPos: "7 / 3"
            },
        ],
        connections: [
            {from: 'programming-concepts', to: 'programming-languages', type: 'straight'},
            {from: 'programming-languages', to: 'web-frameworks', type: 'straight'},
            {from: 'math', to: 'computer-graphics', type: 'straight'},
            {from: 'networking', to: 'web-frameworks', type: 'straight'},
            {from: 'web-frameworks', to: 'full-stack', type: 'straight'},
            {from: 'html-css', to: 'web-frameworks', type: 'straight'},
            {from: 'databases', to: 'full-stack', type: 'straight'},
            {from: 'message-brokers', to: 'full-stack', type: 'straight'},
            {from: 'full-stack', to: 'dev-ops', type: 'straight'},
            {from: 'containers', to: 'dev-ops', type: 'straight'},
            {from: 'os', to: 'sys-admin', type: 'straight'},
        ]
    }
};