const treeDatabase = {
    arts: {
        nodes: [
            //row1
            {
                id: "design-concepts",
                label: "Design<br>Concepts",
                icon: "Art_Icons/Design_Concepts.png",
                title: "Design Concepts",
                type: "Arts Skill",
                req: "",
                desc: "My understanding of Design Concepts, such as Gestalt, was established in my Associate's program.",
                descLong: "My understanding of Design Concepts, such as Gestalt, was established in my Associate's program. Lorem Ipsum",
                points: "3/3",
                pointClass: "full",
                gridPos: "1 / 2"
            },
            {
                id: "sketching",
                label: "Sketching",
                icon: "Art_Icons/Sketching.png",
                title: "Sketching",
                type: "Arts Skill",
                req: "",
                desc: `I have doodled periodically throughout my life. In my Associate's program, I took two classes 
                that involved sketching with pencil, colored pencils, and graphite.`,
                descLong: "I have doodled periodically throughout my life. In my Associate's program, I took two classes that involved sketching with pencil, colored pencils, and graphite.Lorem Ipsum",
                points: "3/3",
                pointClass: "full",
                gridPos: "1 / 3"
            },
            //row2
            {
                id: "writing",
                label: "Writing",
                icon: "Art_Icons/Writing.png",
                title: "Writing",
                type: "Arts Skill",
                req: "Requires Something",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "3/3",
                pointClass: "full",
                gridPos: "2 / 1"
            },
            {
                id: "audio",
                label: "Audio",
                icon: "Art_Icons/Audio.png",
                title: "Audio",
                type: "Arts Skill",
                req: "Requires Something",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "0/3",
                pointClass: "zero",
                gridPos: "2 / 2"
            },
            {
                id: "figure-drawing",
                label: "Figure<br>Drawing",
                icon: "Art_Icons/Figure_Drawing.png",
                title: "Figure Drawing",
                type: "Arts Skill",
                req: "Requires Something",
                desc: `In my Associate's program, I took a course called Drawing the Human Form. In it, we drew on
                    easels using live models. I continued to explore gesture drawing for some time after my program, using
                    pencils.`,
                descLong: "Lorem Ipsum",
                points: "3/3",
                pointClass: "full",
                gridPos: "2 / 4"
            },
            //row3
            {
                id: "art-3d",
                label: "3D Art",
                icon: "Art_Icons/3D.png",
                title: "3D Art",
                type: "Arts Skill",
                req: "Requires Something",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "1/3",
                pointClass: "partial",
                gridPos: "3 / 2"
            },
            {
                id: "art-2d",
                label: "2D Art",
                icon: "Art_Icons/2D.png",
                title: "2D Art",
                type: "Arts Skill",
                req: "Requires Something",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "3/3",
                pointClass: "full",
                gridPos: "3 / 3"
            },
            //row4
            {
                id: "texture-uv",
                label: "Texture<br>UV",
                icon: "Art_Icons/texture.png",
                title: "Texture UV",
                type: "Arts Skill",
                req: "Requires Something",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "0/3",
                pointClass: "zero",
                gridPos: "4 / 2"
            },
            {
                id: "raster",
                label: "Raster",
                icon: "Art_Icons/Raster.png",
                title: "Raster",
                type: "Arts Skill",
                req: "Requires Something",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "0/3",
                pointClass: "zero",
                gridPos: "4 / 3"
            },
            {
                id: "vector",
                label: "Vector",
                icon: "Art_Icons/Vector.png",
                title: "Vector",
                type: "Arts Skill",
                req: "Requires Something",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "2/3",
                pointClass: "partial",
                gridPos: "4 / 4"
            },
            //row5
            {
                id: "rigging",
                label: "Rigging",
                icon: "Art_Icons/rigging.png",
                title: "Rigging",
                type: "Arts Skill",
                req: "Requires Something",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "2/3",
                pointClass: "partial",
                gridPos: "5 / 2"
            },
            {
                id: "anim-3d",
                label: "3D Anim.",
                icon: "Art_Icons/3D_anim.png",
                title: "3D Anim.",
                type: "Arts Skill",
                req: "Requires 3D Art and Rigging",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "2/3",
                pointClass: "partial",
                gridPos: "5 / 1"
            },
            {
                id: "anim-2d",
                label: "2D Anim.",
                icon: "Art_Icons/2D_anim.png",
                title: "2D Anim.",
                type: "Arts Skill",
                req: "Requires Something",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "2/3",
                pointClass: "partial",
                gridPos: "5 / 3"
            },
            //row6
            {
                id: "ui-ux",
                label: "UI/UX<br>Design",
                icon: "Art_Icons/ui_ux.png",
                title: "UI/UX Design",
                type: "Arts Skill",
                req: "Requires Something",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "2/3",
                pointClass: "partial",
                gridPos: "6 / 2"
            },
            //row7
            {
                id: "web-design",
                label: "Web<br>Design",
                icon: "Art_Icons/web_design.png",
                title: "Web Design",
                type: "Arts Skill",
                req: "Requires Something",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "2/3",
                pointClass: "partial",
                gridPos: "7 / 2"
            },
        ],
        connections: [
            {from: 'sketching', to: 'art-2d', type: 'straight'},
            {from: 'sketching', to: 'figure-drawing', type: 'elbow'},
            {from: 'art-3d', to: 'texture-uv', type: 'straight'},
            {from: 'art-3d', to: 'anim-3d', type: 'left-elbow'},
            {from: 'art-2d', to: 'raster', type: 'straight'},
            {from: 'art-2d', to: 'vector', type: 'elbow'},
            {from: 'raster', to: 'anim-2d', type: 'straight'},
            {from: 'rigging', to: 'anim-3d', type: 'straight'},
            {from: 'rigging', to: 'anim-2d', type: 'straight'},
            {from: 'ui-ux', to: 'web-design', type: 'straight'},
        ]
    },
    games: {
        nodes: [
            //row1
            {
                id: "game-fundamentals",
                label: "Game<br>Design<br> Fundamentals",
                icon: "Game_Icons/gd_fundamentals.png",
                title: "Game Design Fundamentals",
                type: "Games Skill",
                req: "",
                desc: "My understanding of Design Concepts...",
                descLong: "Lorem Ipsum",
                points: "3/3",
                pointClass: "full",
                gridPos: "1 / 2"
            },
            //row2
            {
                id: "narrative-design",
                label: "Narrative<br>Design",
                icon: "Game_Icons/narrative.png",
                title: "Narrative Design",
                type: "Games Skill",
                req: "Requires Game Design Fundamentals",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "0/3",
                pointClass: "zero",
                gridPos: "2 / 1"
            },
            {
                id: "system-design",
                label: "System<br>Design",
                icon: "Game_Icons/system_design.png",
                title: "System Design",
                type: "Games Skill",
                req: "Requires Game Design Fundamentals",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "3/3",
                pointClass: "full",
                gridPos: "2 / 2"
            },
            {
                id: "level-design",
                label: "Level<br>Design",
                icon: "Game_Icons/level_design.png",
                title: "Level Design",
                type: "Level Design",
                req: "Requires Something",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "3/3",
                pointClass: "full",
                gridPos: "2 / 3"
            },
            //row3
            {
                id: "digital",
                label: "Digital<br>Design",
                icon: "Game_Icons/digital_design.png",
                title: "Digital Design",
                type: "Games Skill",
                req: "",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "1/3",
                pointClass: "partial",
                gridPos: "3 / 2"
            },
            {
                id: "tabletop",
                label: "Tabletop<br>Design",
                icon: "Game_Icons/tabletop_design.png",
                title: "Tabletop Design",
                type: "Arts Skill",
                req: "",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "3/3",
                pointClass: "full",
                gridPos: "3 / 4"
            },
            //row4
            {
                id: "rapid-prototyping",
                label: "Rapid<br>Prototyping",
                icon: "Game_Icons/prototyping.png",
                title: "Rapid Prototyping",
                type: "Games Skill",
                req: "Requires Tabletop Design",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "2/3",
                pointClass: "partial",
                gridPos: "4 / 4"
            },
            //row5
            {
                id: "gameplay-programming",
                label: "Gameplay<br>Programming",
                icon: "Game_Icons/gameplay_programming.png",
                title: "Gameplay Programming",
                type: "Games Skill",
                req: "Requires Digital Design",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "2/3",
                pointClass: "partial",
                gridPos: "5 / 2"
            },
            //row6
            {
                id: "unity",
                label: "Unity<br>Game<br>Engine",
                icon: "Game_Icons/Unity.png",
                title: "Unity Game Engine",
                type: "Games Skill",
                req: "Requires Digital Design",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "0/3",
                pointClass: "zero",
                gridPos: "6 / 1"
            },
            {
                id: "godot",
                label: "Godot<br>Game<br>Engine",
                icon: "Game_Icons/Godot.png",
                title: "Godot Game Engine",
                type: "Games Skill",
                req: "Requires Digital Design",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "0/3",
                pointClass: "zero",
                gridPos: "6 / 2"
            },
            {
                id: "unreal",
                label: "Unreal<br>Game<br>Engine",
                icon: "Game_Icons/Unreal.png",
                title: "Unreal Game Engine",
                type: "Games Skill",
                req: "Requires Digital Design",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "2/3",
                pointClass: "partial",
                gridPos: "6 / 3"
            },
            {
                id: "game-process",
                label: "Game<br>Development<br>Process",
                icon: "Game_Icons/gd_process.png",
                title: "Game Development Process",
                type: "Games Skill",
                req: "",
                desc: "I have doodled periodically throughout my life. In my Associate's program...",
                descLong: "Lorem Ipsum",
                points: "3/3",
                pointClass: "full",
                gridPos: "6 / 4"
            },
            //row7
            {
                id: "pitching",
                label: "Pitching",
                icon: "Game_Icons/pitching.png",
                title: "Pitching",
                type: "Games Skill",
                req: "Requires Game Development Process",
                desc: "This description is entirely temporary. This is a skill. I learned it. Lorem Ipsum is simply placeholder latin text...",
                descLong: "Lorem Ipsum",
                points: "1/3",
                pointClass: "partial",
                gridPos: "7 / 4"
            },
        ],
        connections: [
            {from: 'game-fundamentals', to: 'narrative-design', type: 'left-elbow'},
            {from: 'game-fundamentals', to: 'system-design', type: 'straight'},
            {from: 'game-fundamentals', to: 'level-design', type: 'elbow'},
            {from: 'digital', to: 'gameplay-programming', type: 'straight'},
            {from: 'tabletop', to: 'rapid-prototyping', type: 'straight'},
            {from: 'gameplay-programming', to: 'unity', type: 'left-elbow'},
            {from: 'gameplay-programming', to: 'godot', type: 'straight'},
            {from: 'gameplay-programming', to: 'unreal', type: 'elbow'},
            {from: 'game-process', to: 'pitching', type: 'straight'},
        ]
    },
    computers: {
        nodes: [
            //row1
            {
                id: "architecture",
                label: "Architecture",
                icon: "Computer_Icons/architecture.png",
                title: "Architecture",
                type: "Computers Skill",
                req: "",
                desc: "How computer hardware and software interface at a low level, including interfacing with RAM and CPU, threading, and other related concepts.",
                descLong: "I have learned about the high-level interactions between computer hardware through academic coursework and personal study.<br><br>My formal study of architecture is currently in progress, as I am registered for Introduction to Machine Organization and Assembly Language, alongside several Electrical and Computer Engineering courses.",
                points: "1/3",
                pointClass: "partial",
                gridPos: "1 / 1"
            },
            {
                id: "programming-concepts",
                label: "Programming<br>Concepts",
                icon: "Computer_Icons/concepts.png",
                title: "Programming Concepts",
                type: "Computers Skill",
                req: "",
                desc: "The theoretical and structural paradigms of writing software, including object-oriented design, algorithms, and systems programming.",
                descLong: "I have a foundation in programming concepts established through academic coursework and practical application.<br><br>I have taken university courses in Object-Oriented Design, Systems Programming Concepts, and Algorithms. I apply these structures to author game logic and have helped to architect scalable deployment systems in a professional environment.",
                points: "3/3",
                pointClass: "full",
                gridPos: "1 / 2"
            },
            //row2
            {
                id: "dev-process",
                label: "Development<br>Process",
                icon: "Computer_Icons/dev_process.png",
                title: "Development Process",
                type: "Computers Skill",
                req: "",
                desc: "The methodologies and pipelines used to plan, construct, test, and deploy software in a professional environment.",
                descLong: "I gained experience with the software development process as a Software Engineering Contractor at Cisco and regularly use practices such as version control in my personal projects.<br><br>I have experience with Git, GitHub, and Jira in the context of professional teams.",
                points: "3/3",
                pointClass: "full",
                gridPos: "2 / 1"
            },
            {
                id: "programming-languages",
                label: "Programming<br>Languages",
                icon: "Computer_Icons/programming_languages.png",
                title: "Programming Languages",
                type: "Computers Skill",
                req: "Requires Programming Concepts",
                desc: "Proficiency in coding languages used across software engineering, scripting, web development, and game development.",
                descLong: "I am proficient in Python and Bash from my time engineering deployment pipelines at Cisco. Academically, I have utilized Java and C for algorithms and systems programming<br><br>I have experience with multiple programming languages from academic and personal study, and I regularly learn new languages as needed, with a preference for Python.",
                points: "3/3",
                pointClass: "full",
                gridPos: "2 / 2"
            },
            {
                id: "math",
                label: "Math",
                icon: "Computer_Icons/math.png",
                title: "Math",
                type: "Computers Skill",
                req: "",
                desc: "Mathematical foundations critical for computer science, including calculus, linear algebra, discrete math, and probability.",
                descLong: "I have completed university-level coursework up to Calculus IV, as well as Discrete Mathematics, Applied Statistics, Probability, and Linear Algebra.",
                points: "3/3",
                pointClass: "full",
                gridPos: "2 / 4"
            },
            //row3
            {
                id: "networking",
                label: "Networking",
                icon: "Computer_Icons/networking.png",
                title: "Networking",
                type: "Computers Skill",
                req: "",
                desc: "The protocols and infrastructure that allow devices and systems to communicate across networks.",
                //also read that whole book cisco networking
                descLong: "At Cisco, I worked directly with network infrastructures, engineering telemetry platforms that handled real-time data from approximately 2,500 routers.<br><br>To supplement this enterprise experience with formal theory, I am enrolled in a Computer Networks course. I have read Cisco Networking Simplified and am familiar with networking concepts such as the layers of the OSI Model. I have also hosted projects using GitHub Pages and Node.js.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "3 / 1"
            },
            {
                id: "web-frameworks",
                label: "Web<br>Frameworks",
                icon: "Computer_Icons/web_frameworks.png",
                title: "Web Frameworks",
                type: "Computers Skill",
                req: "Requires Programming Languages",
                desc: "Utilizing architectural frameworks to develop, maintain, and scale web applications and services.",
                descLong: "My primary experience with web frameworks involves Django, which I utilized at Cisco to maintain deployment pipelines handling real-time router telemetry. I also have familiarity with React and AngularJS.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "3 / 2"
            },
            {
                id: "html-css",
                label: "HTML/<br>CSS",
                icon: "Computer_Icons/html.png",
                title: "HTML/CSS",
                type: "Computers Skill",
                req: "",
                desc: "The fundamental markup and styling languages used to structure and visually format content across the web.",
                descLong: "I am comfortable using HTML and CSS to build user interfaces and web content. I have created several web projects, including this portfolio website, using HTML, CSS, and JavaScript. I have also created a text-based game using Twine integrated with custom HTML and CSS, and I have exported games to HTML.",
                points: "3/3",
                pointClass: "full",
                gridPos: "3 / 3"
            },
            //row4
            {
                id: "databases",
                label: "Databases",
                icon: "Computer_Icons/databases.png",
                title: "Databases",
                type: "Computers Skill",
                req: "",
                desc: "Structuring, querying, and maintaining data storage systems for applications.",
                descLong: "During my time at Cisco, I architected containerized infrastructure configurations that supported router data visualization. This required working directly with TimescaleDB, PostgreSQL, and Redis. I have taken online courses using SQL and will be taking Database Systems at the university level.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "4 / 1"
            },
            {
                id: "full-stack",
                label: "Full<br>Stack<br>Development",
                icon: "Computer_Icons/fullstack.png",
                title: "Full Stack Development",
                type: "Computers Skill",
                req: "Requires Web Frameworks, Databases, and Message Brokers",
                desc: "Developing and integrating front-end user interfaces with back-end infrastructures of software applications.",
                descLong: "My engineering experience at Cisco required an understanding of the full stack to facilitate deployments. I was responsible for integrating back-end Django pipelines, databases, and message brokers to ensure the front-end telemetry platforms functioned reliably.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "4 / 2"
            },
            {
                id: "message-brokers",
                label: "Message<br>Brokers",
                icon: "Computer_Icons/message.png",
                title: "Message Brokers",
                type: "Computers Skill",
                req: "",
                desc: "Intermediary software modules that route, translate, and manage real-time data streams between distributed applications.",
                descLong: "To manage real-time router telemetry at Cisco, we utilized RabbitMQ and Kafka. These message brokers were essential in ensuring that data streams from thousands of routers were processed reliably without dropping telemetry payloads.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "4 / 3"
            },
            //row5
            {
                id: "dev-ops",
                label: "Dev Ops",
                icon: "Computer_Icons/dev_ops.png",
                title: "Dev Ops",
                type: "Computers Skill",
                req: "Requires Full Stack Development",
                desc: "The alignment of software development and IT operations to optimize CI/CD workflows and provide continuous delivery.",
                descLong: "As a deployment contractor for Cisco, I maintained Docker-based pipelines and engineered multi-stage deployment strategies. I developed custom Bash and Python automation that reduced deployment latency and minimized manual intervention for complex integrations.",
                points: "3/3",
                pointClass: "full",
                gridPos: "5 / 2"
            },
            {
                id: "containers",
                label: "Containers",
                icon: "Computer_Icons/containers.png",
                title: "Containers",
                type: "Computers Skill",
                req: "",
                desc: "Packaging software code and its dependencies into isolated units to ensure consistent execution across different environments.",
                descLong: "I have professional experience architecting containerized infrastructure using Docker and Kubernetes. At Cisco, I designed and maintained Docker-based pipelines to support deployments, streamlining environments for distributed teams.",
                points: "3/3",
                pointClass: "full",
                gridPos: "5 / 3"
            },
            //row6
            {
                id: "os",
                label: "Operating<br>Systems",
                icon: "Computer_Icons/os.png",
                title: "Operating Systems",
                type: "Computers Skill",
                req: "",
                desc: "Proficiency in navigating, configuring, and developing within major operating systems.",
                descLong: "I am comfortable developing and troubleshooting across Windows, macOS, and Linux/Unix environments. Professionally, I utilized Unix for deployment scripting at Cisco. To deepen my structural and theoretical understanding of these environments, I will be taking a dedicated Operating Systems course in the future.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "6 / 1"
            },
            {
                id: "computer-graphics",
                label: "Computer<br>Graphics",
                icon: "Computer_Icons/CG.png",
                title: "Computer Graphics",
                type: "Computers Skill",
                req: "Requires Math",
                desc: "Generating, rendering, and manipulating visual imagery using programmatic mathematics and graphic APIs.",
                descLong: "I have established a foundation in computer graphics through academic coursework at WPI. I have executed matrix transformations in WebGL to render scenes, and I am enrolled in Computer Graphics to expand my knowledge of rendering techniques. I will also be taking Computer Animation in the future as a direct follow-up to my WebGL coursework.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "6 / 4"
            },
            //row7
            {
                id: "sys-admin",
                label: "System<br>Administration",
                icon: "Computer_Icons/sysadmin.png",
                title: "System Administration",
                type: "Computers Skill",
                req: "Requires Operating Systems",
                desc: "Configuring, maintaining, and operating computer systems, servers, and automated protocols for distributed teams.",
                descLong: "While my background is centered on software engineering and DevOps, these roles often require system administration. I have experience setting up and troubleshooting servers and virtual machines in clustered environments. This work involved handling administrative tasks such as disk partitioning, configuring networking, and authoring standard operating procedures to ensure system stability.",
                points: "2/3",
                pointClass: "partial",
                gridPos: "7 / 1"
            },
            {
                id: "docs",
                label: "Documentation",
                icon: "Computer_Icons/documentation.png",
                title: "Documentation",
                type: "Computers Skill",
                req: "",
                desc: "Writing and maintaining structured technical guides, deployment protocols, and project design documents.",
                descLong: "At Cisco, I authored technical documentation to standardize deployment protocols for distributed engineering teams.",
                points: "3/3",
                pointClass: "full",
                gridPos: "7 / 2"
            },
            {
                id: "ai",
                label: "Artificial<br>Intelligence",
                icon: "Computer_Icons/AI.png",
                title: "Artificial Intelligence",
                type: "Computers Skill",
                req: "",
                desc: "The foundational logic and algorithmic structures required to simulate decision-making or intelligent behavior in software.",
                descLong: "My background as a programmer and game developer provides a foundation in the logic structures, state machines, and algorithmic decision-making that serve as the building blocks for AI. To formally develop this skill set, I will be taking three dedicated classes next year: Machine Learning, Introduction to Artificial Intelligence, and Artificial Intelligence in Games.",
                points: "1/3",
                pointClass: "partial",
                gridPos: "7 / 3"
            },
        ],
        connections: [
            {from: 'programming-concepts', to: 'programming-languages', type: 'straight'},
            {from: 'programming-languages', to: 'web-frameworks', type: 'straight'},
            {from: 'math', to: 'computer-graphics', type: 'straight'},
            {from: 'networking', to: 'web-frameworks', type: 'straight'},
            {from: 'web-frameworks', to: 'full-stack', type: 'straight'},
            {from: 'html-css', to: 'web-frameworks', type: 'straight'},
            {from: 'databases', to: 'full-stack', type: 'straight'},
            {from: 'message-brokers', to: 'full-stack', type: 'straight'},
            {from: 'full-stack', to: 'dev-ops', type: 'straight'},
            {from: 'containers', to: 'dev-ops', type: 'straight'},
            {from: 'os', to: 'sys-admin', type: 'straight'},
        ]
    }
};